// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveView is a ledger entry for a produced archive.
 */
export interface ArchiveView {
    "id": string;
    "seq": number;
    "folderName": string;
    "archivePath": string;
    "sourcePath": string;
    "size": number;
    "fileCount": number;
    "status": string;
    "passwordId": string;
    "createdAt": string;
}

/**
 * ItemView is a vault entry without its secret.
 */
export interface ItemView {
    "id": string;
    "label": string;
    "createdAt": string;
}

/**
 * TaskInput is the editable form for a task.
 */
export interface TaskInput {
    "id": string;
    "name": string;
    "sourceDir": string;
    "destDir": string;
    "codec": string;
    "level": number;
    "encrypt": boolean;
    "headerEncrypt": boolean;
    "splitSize": number;
    "passwordMode": string;
    "passwordLength": number;
    "passwordFixed": string;
    "dedupRule": string;
    "namePrefix": string;
    "nameSuffix": string;
    "seqStart": number;
    "include": string;
    "exclude": string;
}

/**
 * TaskView is a stored task plus derived statistics.
 */
export interface TaskView {
    "id": string;
    "name": string;
    "sourceDir": string;
    "destDir": string;
    "codec": string;
    "level": number;
    "encrypt": boolean;
    "headerEncrypt": boolean;
    "splitSize": number;
    "passwordMode": string;
    "passwordLength": number;
    "dedupRule": string;
    "namePrefix": string;
    "nameSuffix": string;
    "seqStart": number;
    "nextSeq": number;
    "include": string;
    "exclude": string;
    "archiveCount": number;
    "enabled": boolean;
}

/**
 * ToolStatus reports archiver availability.
 */
export interface ToolStatus {
    "available": boolean;
    "path": string;
    "version": string;
    "codecs": string[] | null;
    "error": string;
}

/**
 * VaultStatus describes the encrypted vault state.
 */
export interface VaultStatus {
    "path": string;
    "exists": boolean;
    "unlocked": boolean;
}
