// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskService is the frontend-facing API for tasks, runs and archives.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppVersion returns the application version.
 */
export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1222498361);
}

/**
 * Archives returns the ledger for a task ("" = all tasks).
 */
export function Archives(taskID: string): $CancellablePromise<$models.ArchiveView[] | null> {
    return $Call.ByID(3461366187, taskID);
}

/**
 * Cancel stops the running task.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(1702830246);
}

/**
 * Delete removes a task (its archive ledger is preserved).
 */
export function Delete(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3871585583, taskID);
}

/**
 * ExportExcel writes the archive ledger (with passwords) to an .xlsx file.
 * taskID "" exports all tasks. The vault must be unlocked when any archive has
 * a stored password. Returns the number of rows written.
 */
export function ExportExcel(taskID: string, outPath: string): $CancellablePromise<number> {
    return $Call.ByID(1003693845, taskID, outPath);
}

/**
 * Extract unpacks an archive into outDir using its stored password.
 */
export function Extract(archivePath: string, outDir: string, passwordID: string): $CancellablePromise<void> {
    return $Call.ByID(3330811173, archivePath, outDir, passwordID);
}

/**
 * Get returns a single task by id.
 */
export function Get(taskID: string): $CancellablePromise<$models.TaskView> {
    return $Call.ByID(2526665920, taskID);
}

/**
 * ImportLegacy imports a legacy config.properties + db.sqlite3. The vault must
 * be unlocked. Returns a short summary string.
 */
export function ImportLegacy(configPath: string): $CancellablePromise<string> {
    return $Call.ByID(964441658, configPath);
}

/**
 * IsPaused reports whether the running task is paused.
 */
export function IsPaused(): $CancellablePromise<boolean> {
    return $Call.ByID(2697590534);
}

/**
 * IsRunning reports whether a run is in progress.
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(447765563);
}

/**
 * List returns all tasks with their archive counts.
 */
export function List(): $CancellablePromise<$models.TaskView[] | null> {
    return $Call.ByID(2092824044);
}

/**
 * Pause stops the running task after the current folder finishes.
 */
export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(3086421582);
}

/**
 * PickDirectory opens a native folder chooser.
 */
export function PickDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(2564224224, title);
}

/**
 * PickLegacyConfig opens a chooser for the legacy config.properties file.
 */
export function PickLegacyConfig(): $CancellablePromise<string> {
    return $Call.ByID(3635063024);
}

/**
 * PickSaveFile opens a native save dialog for an .xlsx file.
 */
export function PickSaveFile(title: string, defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(3296443734, title, defaultName);
}

/**
 * Resume continues a paused task.
 */
export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(2428753175);
}

/**
 * Run starts a task asynchronously. Progress is streamed via "job:event".
 */
export function Run(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3353709281, taskID);
}

/**
 * Save creates or updates a task and returns its id.
 */
export function Save($in: $models.TaskInput): $CancellablePromise<string> {
    return $Call.ByID(3316906593, $in);
}

/**
 * ToolStatus reports the 7-Zip engine availability.
 */
export function ToolStatus(): $CancellablePromise<$models.ToolStatus> {
    return $Call.ByID(2692418880);
}

/**
 * Verify tests an archive's integrity using its stored password.
 */
export function Verify(archivePath: string, passwordID: string): $CancellablePromise<void> {
    return $Call.ByID(1852093433, archivePath, passwordID);
}
