// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VaultService is the frontend-facing API for the encrypted password vault.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create initialises a new vault with the given master password.
 */
export function Create(master: string): $CancellablePromise<void> {
    return $Call.ByID(3576119441, master);
}

/**
 * Generate returns a random password suggestion.
 */
export function Generate(length: number, symbols: boolean): $CancellablePromise<string> {
    return $Call.ByID(3069524254, length, symbols);
}

/**
 * List returns vault entries (no secrets).
 */
export function List(): $CancellablePromise<$models.ItemView[] | null> {
    return $Call.ByID(2700198509);
}

/**
 * Lock wipes the data key from memory.
 */
export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(337357262);
}

/**
 * Reveal returns the plaintext password for an item.
 */
export function Reveal(id: string): $CancellablePromise<string> {
    return $Call.ByID(2833000476, id);
}

/**
 * Status reports whether the vault file exists and is currently unlocked.
 */
export function Status(): $CancellablePromise<$models.VaultStatus> {
    return $Call.ByID(3998809027);
}

/**
 * Unlock opens and unlocks the vault.
 */
export function Unlock(master: string): $CancellablePromise<void> {
    return $Call.ByID(463265505, master);
}

/**
 * Update changes an entry's label and password (the note is preserved).
 */
export function Update(id: string, label: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(1344403456, id, label, password);
}
